const express=require('express');
const router=express.Router();
const {fetchStats, createPoliceOfficer, getFilteredPolice, deletePoliceOfficer, updatePoliceRank,getPolicePersonnelAnalysis,getComplaintsByBadge,getComplaintsByStationPincode}=require('../controller/adminController');
const { authenticate, authorise } = require('../middleware/authMiddleware');
router.get('/fetchStats',authenticate,authorise(['admin']),fetchStats);
router.post('/createPoliceOfficer',authenticate,authorise(['admin']),createPoliceOfficer);
router.get('/getFilteredPolice',authenticate,authorise(['admin']),getFilteredPolice);
router.delete('/deletePoliceOfficer',authenticate,authorise(['admin']),deletePoliceOfficer);
router.put('/updatePoliceRank',authenticate,authorise(['admin']),updatePoliceRank);
router.get('/getPolicePersonnelAnalysis',authenticate,authorise(['admin']),getPolicePersonnelAnalysis);
router.get('/getComplaintsByBadge/:badgeNumber',authenticate,authorise(['admin']),getComplaintsByBadge);
router.get('/getComplaintsByStationPincode/:pincode',authenticate,authorise(['admin']),getComplaintsByStationPincode);
module.exports=router;