export const crimeTypes = [
  'Assault', 'Domestic Violence', 'Attempt to Murder', 'Murder',
  'Kidnapping / Abduction', 'Sexual Assault / Rape',
  'Theft', 'Burglary / Break-in', 'Robbery', 'Vandalism', 'Arson', 'Trespassing',
  'Cyber Bullying', 'Online Fraud / Scam', 'Identity Theft', 'Phishing Attack',
  'Cyberstalking', 'Hacking / Unauthorized Access',
  'Missing Adult', 'Missing Child', 'Human Trafficking Suspicion',
  'Drunk and Disorderly Conduct', 'Public Nuisance', 'Rioting', 'Illegal Gathering / Protest',
  'Bribery / Corruption', 'Bank Fraud', 'Fake Currency', 'Ponzi / Investment Scam',
  'Tax Evasion', 'Verbal Abuse', 'Workplace Harassment', 'Stalking',
  'Blackmail / Extortion', 'Drug Possession', 'Drug Trafficking', 'Illegal Alcohol Sale',
  'Hit and Run', 'Drunk Driving', 'Reckless Driving', 'Road Rage Incident',
  'Animal Abuse', 'Child Abuse', 'Suicide Attempt Reporting', 'Suspicious Activity', 'Other'
];
// leadTitles.js

export const leadTitles = [
  "Animal Injured on Road",
  "Bike Racing on Road",
  "Broken Road or Pothole",
  "Broken Traffic Signal",
  "Bus Overcrowded Dangerously",
  "Car Accident Seen",
  "Car Driving Over Speed Limit",
  "Car Parked Illegally",
  "Car With Broken Number Plate",
  "Child Begging Alone",
  "Crowd Gathering Suddenly",
  "Dangerous Dog Roaming",
  "Drunk Driver Sighting",
  "Elderly Person Needing Help",
  "Electricity Wire Hanging Low",
  "Fire or Smoke Seen",
  "Garbage Dumped on Road",
  "Group of People Fighting",
  "Illegal Construction Activity",
  "Large Gathering Without Permission",
  "Loud Argument in Public",
  "Loud Noise or Disturbance",
  "Lost Child Spotted",
  "Man Following Woman",
  "Person Asking for Help",
  "Person Being Beaten",
  "Person Carrying Weapon",
  "Person Falling Unconscious",
  "Person Running Suspiciously",
  "Person Selling Drugs",
  "Person Selling Fake Products",
  "Person Taking Photos Suspiciously",
  "Person Throwing Stones at Vehicles",
  "Possible Kidnapping Scene",
  "Public Harassment Incident",
  "Road Blocked by Protest",
  "Shop Selling Illegal Items",
  "Snake or Wild Animal Sighting",
  "Speeding Truck or Lorry",
  "Street Light Not Working",
  "Stranger Knocking Doors Randomly",
  "Stranger Trying to Enter Houses",
  "Theft in Progress",
  "Tree Fallen on Road",
  "Unauthorized Vendor on Footpath",
  "Unknown Person Lurking Around",
  "Vehicle Abandoned for Long Time",
  "Vehicle Emitting Excessive Smoke",
  "Woman or Child Crying Alone"
];



export const  crimeFacts = [
    // General Crime Statistics (Based on NCRB 2022)
    "India registered over 58.2 lakh cognizable crimes in 2022.",
    "The overall crime rate in India was 422.2 per lakh population in 2022.",
    "A total of 35.6 lakh crimes were registered under the Indian Penal Code (IPC) in 2022.",
    "Over 22.7 lakh crimes were registered under Special & Local Laws (SLL) in 2022.",
    "Crime registration in India saw a decline of 4.5% in 2022 compared to 2021.",
    "The rate of violent crimes in India was 30.2 per lakh population in 2022.",
    "Chargesheeting rate for IPC crimes stood at 72.3% in 2022.",
    "The conviction rate for IPC crimes in India is approximately 57%.",
    "On average, India reports more than 10 IPC crimes every minute.",
    "The category 'Hurt' accounted for the highest number of IPC crimes against the body.",
    "Cases of 'Theft' (Section 379 IPC) constitute the largest portion of property crimes.",
    "An average of 78 people were murdered every day in India during 2022.",
    "The majority of cognizable crimes are registered under 'Theft', 'Hurt', and 'Causing Death by Negligence'.",
    "Over 1.7 lakh cases of 'Causing Death by Negligence' were reported in 2022.",
    "The number of 'Rioting' cases saw a decline in 2022 compared to previous years.",

    // State & City Specifics (Based on NCRB 2022)
    "Uttar Pradesh reported the highest number of total crimes in 2022.",
    "Delhi City has the highest rate of total cognizable crimes among metropolitan cities.",
    "Kolkata was reported as the safest city among metropolises for the third consecutive year in 2022.",
    "Kerala has the highest crime rate (IPC+SLL) among all states.",
    "Nagaland reported the lowest number of IPC crimes in 2022.",
    "Maharashtra recorded the highest number of cases under Special and Local Laws (SLL).",
    "Jaipur city has the highest rate of violent crimes among 19 metropolitan cities.",
    "The highest number of kidnapping and abduction cases were reported in Uttar Pradesh.",
    "Madhya Pradesh reported the highest number of cases of 'grievous hurt'.",
    "Tamil Nadu registered the most cases of 'Causing Death by Negligence'.",
    "Rajasthan reported the highest number of rape cases in 2022.",
    "Delhi reported the highest rate of crimes against women among all Union Territories.",
    "West Bengal recorded the highest number of cases of 'Cruelty by Husband or His Relatives'.",
    "Bihar has the highest rate of murder cases per lakh population.",
    "Mumbai reported the highest number of economic offences among metropolitan cities.",

    // Crimes Against Women (Based on NCRB 2022 & NFHS-5)
    "A crime against a woman is reported in India every 70 seconds.",
    "India registered 4,45,256 cases of crime against women in 2022.",
    "The rate of crime against women per lakh population stood at 66.4 in 2022.",
    "The majority of crimes against women are 'Cruelty by Husband or His Relatives' (31.4%).",
    "'Kidnapping & Abduction of Women' constitutes 19.2% of crimes against them.",
    "'Assault on Women with Intent to Outrage her Modesty' accounts for 18.7% of cases.",
    "The crime of 'Rape' (Sec. 376 IPC) accounts for 7.1% of all crimes against women.",
    "An average of 86 rape cases were reported daily in India during 2022.",
    "In over 96% of rape cases, the offenders were known to the victims.",
    "The chargesheeting rate in rape cases was 76.5% in 2022.",
    "According to NFHS-5, 32% of ever-married women have experienced spousal violence.",
    "Only 14% of women who have experienced physical or sexual violence have sought help.",
    "Uttar Pradesh has the second-highest number of reported crimes against women, after Rajasthan.",
    "The conviction rate for crimes against women is low, at approximately 27.8%.",
    "Dowry-related deaths (Section 304B IPC) claimed over 6,300 lives in 2022.",

    // Cybercrime (Based on NCRB 2022)
    "India saw a 24.4% increase in reported cybercrime cases in 2022.",
    "A total of 65,893 cybercrime cases were registered in 2022.",
    "The primary motive for over 64% of cybercrimes was fraud.",
    "Online financial fraud is the most common type of cybercrime in India.",
    "Telangana reported the highest number of cybercrime cases.",
    "Bengaluru has the highest rate of cybercrimes among metropolitan cities.",
    "The rate of cybercrime per lakh population is 4.8 in India.",
    "Cases of 'Identity Theft' under the IT Act increased significantly in 2022.",
    "Cyberstalking and bullying of women and children saw a 28% rise in 2022.",
    "Phishing attacks account for a significant portion of online financial frauds.",
    "Ransomware attacks in India are growing at an alarming rate, targeting businesses.",
    "Less than 30% of registered cybercrime cases are chargesheeted.",
    "Uttar Pradesh has the second-highest number of cybercrime cases, after Telangana.",
    "ATM fraud and credit/debit card fraud remain prevalent cybercrimes.",
    "Lack of cyber awareness is a major factor contributing to victimization.",

    // Crimes Against Children (Based on NCRB 2022)
    "Over 1.62 lakh cases of crimes against children were reported in 2022.",
    "This represents an 8.7% increase in crimes against children from 2021.",
    "The majority of cases (45.7%) fall under the POCSO Act for sexual offences.",
    "Kidnapping and Abduction constitute 44.5% of crimes against children.",
    "The rate of crime against children per lakh population is 33.6.",
    "An average of 445 crimes against children were reported every day in 2022.",
    "In 98.7% of POCSO cases involving rape, the offender was known to the child victim.",
    "The conviction rate for crimes under the POCSO Act is approximately 39.7%.",
    "Maharashtra reported the highest number of crimes against children.",
    "Child trafficking cases saw a significant increase in 2022.",
    "The chargesheeting rate for crimes against children stood at 69.8% in 2022.",
    "Delhi has the highest rate of crimes against children among Union Territories.",
    "Online grooming and sexual abuse of children are emerging as major threats.",
    "Over 1,200 cases of child marriage were reported in 2022.",
    "Madhya Pradesh has the highest rate of crimes against children among states.",

    // Violent & Property Crimes (Based on NCRB 2022)
    "A total of 4,38,367 violent crimes were registered in 2022.",
    "India reported 28,522 murder cases in 2022.",
    "'Disputes' were the primary motive for murders, accounting for 34.5% of cases.",
    "The conviction rate for murder cases in India is around 43.8%.",
    "Over 1 lakh cases of 'Kidnapping and Abduction' were registered in 2022.",
    "The motive for most kidnappings was 'to compel for marriage'.",
    "Robbery cases saw a slight decrease in 2022.",
    "Dacoity (armed robbery by a group) cases have been steadily declining.",
    "Over 7.5 lakh cases of theft were reported across the country.",
    "Vehicle theft accounts for a large portion of all theft cases.",
    "A vehicle is stolen in India approximately every 8 minutes.",
    "Delhi reports the highest number of vehicle thefts among all cities.",
    "Burglary cases totaled over 95,000 in 2022.",
    "Extortion cases are most prevalent in states like Uttar Pradesh and Bihar.",
    "Arson cases have shown a downward trend over the past few years.",

    // Economic & Other Crimes (Based on NCRB 2022)
    "Economic offences increased by 11.1% in 2022.",
    "Over 1.9 lakh cases of economic offences were registered.",
    "'Forgery, Cheating & Fraud' made up the majority of these cases.",
    "Rajasthan reported the highest number of economic offence cases.",
    "Cases of criminal breach of trust have increased.",
    "Counterfeiting cases, especially of currency, remain a significant concern.",
    "The conviction rate for economic offences is low, at around 24.3%.",
    "Offences against the state, such as sedition, are relatively low in number.",
    "Cases under the Unlawful Activities (Prevention) Act [UAPA] saw a 23% decline in 2022.",
    "Human trafficking cases increased by 2.8% in 2022.",
    "Over 2,200 cases of human trafficking were reported, with 6,533 victims.",
    "The majority of trafficked persons are forced into sexual exploitation or forced labour.",
    "Maharashtra reported the highest number of corruption cases.",
    "Cases under the Prevention of Corruption Act increased by 10.5% in 2022.",
    "Environmental-related offences saw a sharp decline of 32.7% in 2022.",
    "Over 45,000 cases were registered under the Excise Act, mostly in Bihar.",
    "Cases under the Arms Act remain high, with Uttar Pradesh leading.",
    "Drug trafficking cases under the NDPS Act are most prevalent in Punjab.",
    "Fatal road accidents claimed over 1.6 lakh lives in 2022.",
    "The majority of road accidents are due to over-speeding.",
    "Railway accidents caused 11,107 deaths in 2022.",
    "Cases of rioting were highest in Maharashtra.",
    "The police-to-population ratio in India is 152.8 per lakh persons, below the UN-recommended 222.",
    "Forensic science labs in India have a high pendency rate for cases.",
    "There are over 4.7 crore pending cases across all courts in India.",
];