export const crimeTypes = [
  'Assault', 'Domestic Violence', 'Attempt to Murder', 'Murder',
  'Kidnapping / Abduction', 'Sexual Assault / Rape',
  'Theft', 'Burglary / Break-in', 'Robbery', 'Vandalism', 'Arson', 'Trespassing',
  'Cyber Bullying', 'Online Fraud / Scam', 'Identity Theft', 'Phishing Attack',
  'Cyberstalking', 'Hacking / Unauthorized Access',
  'Missing Adult', 'Missing Child', 'Human Trafficking Suspicion',
  'Drunk and Disorderly Conduct', 'Public Nuisance', 'Rioting', 'Illegal Gathering / Protest',
  'Bribery / Corruption', 'Bank Fraud', 'Fake Currency', 'Ponzi / Investment Scam',
  'Tax Evasion', 'Verbal Abuse', 'Workplace Harassment', 'Stalking',
  'Blackmail / Extortion', 'Drug Possession', 'Drug Trafficking', 'Illegal Alcohol Sale',
  'Hit and Run', 'Drunk Driving', 'Reckless Driving', 'Road Rage Incident',
  'Animal Abuse', 'Child Abuse', 'Suicide Attempt Reporting', 'Suspicious Activity', 'Other'
];
// leadTitles.js

export const leadTitles = [
  "Animal Injured on Road",
  "Bike Racing on Road",
  "Broken Road or Pothole",
  "Broken Traffic Signal",
  "Bus Overcrowded Dangerously",
  "Car Accident Seen",
  "Car Driving Over Speed Limit",
  "Car Parked Illegally",
  "Car With Broken Number Plate",
  "Child Begging Alone",
  "Crowd Gathering Suddenly",
  "Dangerous Dog Roaming",
  "Drunk Driver Sighting",
  "Elderly Person Needing Help",
  "Electricity Wire Hanging Low",
  "Fire or Smoke Seen",
  "Garbage Dumped on Road",
  "Group of People Fighting",
  "Illegal Construction Activity",
  "Large Gathering Without Permission",
  "Loud Argument in Public",
  "Loud Noise or Disturbance",
  "Lost Child Spotted",
  "Man Following Woman",
  "Person Asking for Help",
  "Person Being Beaten",
  "Person Carrying Weapon",
  "Person Falling Unconscious",
  "Person Running Suspiciously",
  "Person Selling Drugs",
  "Person Selling Fake Products",
  "Person Taking Photos Suspiciously",
  "Person Throwing Stones at Vehicles",
  "Possible Kidnapping Scene",
  "Public Harassment Incident",
  "Road Blocked by Protest",
  "Shop Selling Illegal Items",
  "Snake or Wild Animal Sighting",
  "Speeding Truck or Lorry",
  "Street Light Not Working",
  "Stranger Knocking Doors Randomly",
  "Stranger Trying to Enter Houses",
  "Theft in Progress",
  "Tree Fallen on Road",
  "Unauthorized Vendor on Footpath",
  "Unknown Person Lurking Around",
  "Vehicle Abandoned for Long Time",
  "Vehicle Emitting Excessive Smoke",
  "Woman or Child Crying Alone"
];


