export const crimeTypes = [
  'Assault', 'Domestic Violence', 'Attempt to Murder', 'Murder',
  'Kidnapping / Abduction', 'Sexual Assault / Rape',
  'Theft', 'Burglary / Break-in', 'Robbery', 'Vandalism', 'Arson', 'Trespassing',
  'Cyber Bullying', 'Online Fraud / Scam', 'Identity Theft', 'Phishing Attack',
  'Cyberstalking', 'Hacking / Unauthorized Access',
  'Missing Adult', 'Missing Child', 'Human Trafficking Suspicion',
  'Drunk and Disorderly Conduct', 'Public Nuisance', 'Rioting', 'Illegal Gathering / Protest',
  'Bribery / Corruption', 'Bank Fraud', 'Fake Currency', 'Ponzi / Investment Scam',
  'Tax Evasion', 'Verbal Abuse', 'Workplace Harassment', 'Stalking',
  'Blackmail / Extortion', 'Drug Possession', 'Drug Trafficking', 'Illegal Alcohol Sale',
  'Hit and Run', 'Drunk Driving', 'Reckless Driving', 'Road Rage Incident',
  'Animal Abuse', 'Child Abuse', 'Suicide Attempt Reporting', 'Suspicious Activity', 'Other'
];
// leadTitles.js

export const leadTitles = [
  "Person Running Suspiciously",
  "Car Driving Over Speed Limit",
  "Bike Racing on Road",
  "Group of People Fighting",
  "Animal Injured on Road",
  "Person Carrying Weapon",
  "Unknown Person Lurking Around",
  "Drunk Driver Sighting",
  "Street Light Not Working",
  "Broken Road or Pothole",
  "Car Parked Illegally",
  "Fire or Smoke Seen",
  "Theft in Progress",
  "Person Asking for Help",
  "Loud Noise or Disturbance",
  "Woman or Child Crying Alone",
  "Illegal Construction Activity",
  "Garbage Dumped on Road",
  "Water Leakage or Pipeline Burst",
  "Electricity Wire Hanging Low",
  "Dangerous Dog Roaming",
  "Public Harassment Incident",
  "Person Taking Photos Suspiciously",
  "Car With Broken Number Plate",
  "Vehicle Abandoned for Long Time",
  "Crowd Gathering Suddenly",
  "Road Blocked by Protest",
  "Person Being Beaten",
  "Possible Kidnapping Scene",
  "Person Selling Drugs",
  "Stranger Knocking Doors Randomly",
  "Shop Selling Illegal Items",
  "Car Accident Seen",
  "Child Begging Alone",
  "Man Following Woman",
  "Loud Argument in Public",
  "Broken Traffic Signal",
  "Unauthorized Vendor on Footpath",
  "Tree Fallen on Road",
  "Stranger Trying to Enter Houses",
  "Person Throwing Stones at Vehicles",
  "Bus Overcrowded Dangerously",
  "Vehicle Emitting Excessive Smoke",
  "Person Falling Unconscious",
  "Elderly Person Needing Help",
  "Lost Child Spotted",
  "Snake or Wild Animal Sighting",
  "Speeding Truck or Lorry",
  "Person Selling Fake Products",
  "Large Gathering Without Permission"
];

